---
- hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: add docker repos
      apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-xenial main"

    - name: add docker keys
      apt_key: url=https://apt.dockerproject.org/gpg

    - name: install docker engine
      apt: name=docker-engine update_cache=yes

    - name: add ubuntu to docker group
      user: name=ubuntu groups=docker append=yes

    - name: ensure docker service is running
      service: name=docker state=started enabled=yes

    # dont use docker_image module because there is a bug with py3 (already fix in develop branch)
    - name: pull image
      shell: docker pull ubuntu:latest